const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const getItems = (page, size) => {
    return delay(500).then(() => (
        {
            items: items.slice(0, page*size),
            hasMore: page * size < items.length,
        }
    ));
};

const items = [
    {
        "id": 1,
        "first_name": "Barde",
        "last_name": "Perse",
        "email": "bperse0@flickr.com",
        "gender": "Male",
        "ip_address": "43.43.135.7"
    }, {
        "id": 2,
        "first_name": "Roley",
        "last_name": "Monkhouse",
        "email": "rmonkhouse1@state.gov",
        "gender": "Male",
        "ip_address": "14.5.242.54"
    }, {
        "id": 3,
        "first_name": "Cammy",
        "last_name": "Watson-Brown",
        "email": "cwatsonbrown2@vkontakte.ru",
        "gender": "Male",
        "ip_address": "119.18.30.235"
    }, {
        "id": 4,
        "first_name": "Galina",
        "last_name": "Palumbo",
        "email": "gpalumbo3@upenn.edu",
        "gender": "Female",
        "ip_address": "220.148.94.103"
    }, {
        "id": 5,
        "first_name": "Sharla",
        "last_name": "Ottosen",
        "email": "sottosen4@ustream.tv",
        "gender": "Female",
        "ip_address": "61.35.219.238"
    }, {
        "id": 6,
        "first_name": "Gay",
        "last_name": "Letrange",
        "email": "gletrange5@hatena.ne.jp",
        "gender": "Male",
        "ip_address": "72.37.130.111"
    }, {
        "id": 7,
        "first_name": "Agatha",
        "last_name": "Yendall",
        "email": "ayendall6@vkontakte.ru",
        "gender": "Female",
        "ip_address": "12.102.240.94"
    }, {
        "id": 8,
        "first_name": "Lil",
        "last_name": "Shivell",
        "email": "lshivell7@github.com",
        "gender": "Female",
        "ip_address": "21.72.234.141"
    }, {
        "id": 9,
        "first_name": "Vaclav",
        "last_name": "Yakob",
        "email": "vyakob8@usa.gov",
        "gender": "Male",
        "ip_address": "91.231.137.20"
    }, {
        "id": 10,
        "first_name": "Bevon",
        "last_name": "Lerer",
        "email": "blerer9@aol.com",
        "gender": "Male",
        "ip_address": "15.125.116.236"
    }, {
        "id": 11,
        "first_name": "Herrick",
        "last_name": "Piell",
        "email": "hpiella@4shared.com",
        "gender": "Male",
        "ip_address": "152.83.168.194"
    }, {
        "id": 12,
        "first_name": "Isaac",
        "last_name": "Plose",
        "email": "iploseb@usnews.com",
        "gender": "Male",
        "ip_address": "252.95.54.78"
    }, {
        "id": 13,
        "first_name": "Ninetta",
        "last_name": "Banasiak",
        "email": "nbanasiakc@cbsnews.com",
        "gender": "Female",
        "ip_address": "54.146.145.8"
    }, {
        "id": 14,
        "first_name": "Fayre",
        "last_name": "Steely",
        "email": "fsteelyd@biglobe.ne.jp",
        "gender": "Female",
        "ip_address": "210.103.203.121"
    }, {
        "id": 15,
        "first_name": "Joelie",
        "last_name": "Crowche",
        "email": "jcrowchee@chicagotribune.com",
        "gender": "Female",
        "ip_address": "219.176.57.98"
    }, {
        "id": 16,
        "first_name": "Laurette",
        "last_name": "Neesham",
        "email": "lneeshamf@washingtonpost.com",
        "gender": "Female",
        "ip_address": "230.241.166.105"
    }, {
        "id": 17,
        "first_name": "Andee",
        "last_name": "Kaine",
        "email": "akaineg@webs.com",
        "gender": "Female",
        "ip_address": "89.128.26.151"
    }, {
        "id": 18,
        "first_name": "Haskel",
        "last_name": "Cahill",
        "email": "hcahillh@stumbleupon.com",
        "gender": "Male",
        "ip_address": "246.230.189.19"
    }, {
        "id": 19,
        "first_name": "Henri",
        "last_name": "Sheardown",
        "email": "hsheardowni@purevolume.com",
        "gender": "Male",
        "ip_address": "144.200.59.177"
    }, {
        "id": 20,
        "first_name": "Duffie",
        "last_name": "McNeil",
        "email": "dmcneilj@scribd.com",
        "gender": "Male",
        "ip_address": "19.198.247.233"
    }, {
        "id": 21,
        "first_name": "Arlene",
        "last_name": "Camell",
        "email": "acamellk@toplist.cz",
        "gender": "Female",
        "ip_address": "35.39.121.252"
    }, {
        "id": 22,
        "first_name": "Martie",
        "last_name": "Hullot",
        "email": "mhullotl@microsoft.com",
        "gender": "Female",
        "ip_address": "133.180.51.203"
    }, {
        "id": 23,
        "first_name": "Dionne",
        "last_name": "Cutbirth",
        "email": "dcutbirthm@163.com",
        "gender": "Female",
        "ip_address": "231.237.7.23"
    }, {
        "id": 24,
        "first_name": "Bunny",
        "last_name": "Bowdery",
        "email": "bbowderyn@booking.com",
        "gender": "Female",
        "ip_address": "36.205.252.155"
    }, {
        "id": 25,
        "first_name": "Patty",
        "last_name": "Apfelmann",
        "email": "papfelmanno@apple.com",
        "gender": "Male",
        "ip_address": "227.90.46.85"
    }, {
        "id": 26,
        "first_name": "Pearline",
        "last_name": "Brayfield",
        "email": "pbrayfieldp@oracle.com",
        "gender": "Female",
        "ip_address": "33.99.129.93"
    }, {
        "id": 27,
        "first_name": "Zebulon",
        "last_name": "Relton",
        "email": "zreltonq@friendfeed.com",
        "gender": "Male",
        "ip_address": "239.134.32.255"
    }, {
        "id": 28,
        "first_name": "Kip",
        "last_name": "Clougher",
        "email": "kclougherr@yahoo.co.jp",
        "gender": "Male",
        "ip_address": "186.189.104.245"
    }, {
        "id": 29,
        "first_name": "Glyn",
        "last_name": "MacPherson",
        "email": "gmacphersons@bbb.org",
        "gender": "Male",
        "ip_address": "129.24.214.238"
    }, {
        "id": 30,
        "first_name": "Pippo",
        "last_name": "Sor",
        "email": "psort@tiny.cc",
        "gender": "Male",
        "ip_address": "59.255.1.179"
    }, {
        "id": 31,
        "first_name": "Tait",
        "last_name": "Tschirschky",
        "email": "ttschirschkyu@geocities.jp",
        "gender": "Male",
        "ip_address": "23.152.237.46"
    }, {
        "id": 32,
        "first_name": "Harris",
        "last_name": "Speare",
        "email": "hspearev@admin.ch",
        "gender": "Male",
        "ip_address": "208.134.83.22"
    }, {
        "id": 33,
        "first_name": "Bevan",
        "last_name": "Willox",
        "email": "bwilloxw@vinaora.com",
        "gender": "Male",
        "ip_address": "150.94.149.210"
    }, {
        "id": 34,
        "first_name": "Eleanore",
        "last_name": "Maytom",
        "email": "emaytomx@ustream.tv",
        "gender": "Female",
        "ip_address": "11.12.191.148"
    }, {
        "id": 35,
        "first_name": "Shirleen",
        "last_name": "Sorensen",
        "email": "ssorenseny@statcounter.com",
        "gender": "Female",
        "ip_address": "52.109.28.35"
    }, {
        "id": 36,
        "first_name": "Etan",
        "last_name": "Leys",
        "email": "eleysz@webeden.co.uk",
        "gender": "Male",
        "ip_address": "142.240.153.53"
    }, {
        "id": 37,
        "first_name": "Pasquale",
        "last_name": "Haresnape",
        "email": "pharesnape10@biglobe.ne.jp",
        "gender": "Male",
        "ip_address": "37.9.52.155"
    }, {
        "id": 38,
        "first_name": "Kalvin",
        "last_name": "Silmon",
        "email": "ksilmon11@nps.gov",
        "gender": "Male",
        "ip_address": "79.182.87.18"
    }, {
        "id": 39,
        "first_name": "Dorie",
        "last_name": "Columbine",
        "email": "dcolumbine12@washington.edu",
        "gender": "Male",
        "ip_address": "207.237.68.159"
    }, {
        "id": 40,
        "first_name": "Der",
        "last_name": "Mighele",
        "email": "dmighele13@1und1.de",
        "gender": "Male",
        "ip_address": "69.183.67.216"
    }, {
        "id": 41,
        "first_name": "Rubin",
        "last_name": "Chapelle",
        "email": "rchapelle14@telegraph.co.uk",
        "gender": "Male",
        "ip_address": "113.31.2.254"
    }, {
        "id": 42,
        "first_name": "Kort",
        "last_name": "Chelnam",
        "email": "kchelnam15@live.com",
        "gender": "Male",
        "ip_address": "245.38.112.218"
    }, {
        "id": 43,
        "first_name": "Gaylene",
        "last_name": "Outram",
        "email": "goutram16@github.com",
        "gender": "Female",
        "ip_address": "7.57.37.255"
    }, {
        "id": 44,
        "first_name": "Phaidra",
        "last_name": "Wrates",
        "email": "pwrates17@dion.ne.jp",
        "gender": "Female",
        "ip_address": "24.254.20.155"
    }, {
        "id": 45,
        "first_name": "Tiffie",
        "last_name": "Armytage",
        "email": "tarmytage18@wikimedia.org",
        "gender": "Female",
        "ip_address": "182.197.45.171"
    }, {
        "id": 46,
        "first_name": "Sharity",
        "last_name": "Shallcross",
        "email": "sshallcross19@etsy.com",
        "gender": "Female",
        "ip_address": "34.159.24.60"
    }, {
        "id": 47,
        "first_name": "Stillman",
        "last_name": "Canet",
        "email": "scanet1a@plala.or.jp",
        "gender": "Male",
        "ip_address": "77.87.83.235"
    }, {
        "id": 48,
        "first_name": "Jonas",
        "last_name": "Heigold",
        "email": "jheigold1b@typepad.com",
        "gender": "Male",
        "ip_address": "91.195.174.78"
    }, {
        "id": 49,
        "first_name": "Felicity",
        "last_name": "Arblaster",
        "email": "farblaster1c@naver.com",
        "gender": "Female",
        "ip_address": "155.153.37.247"
    }, {
        "id": 50,
        "first_name": "Archie",
        "last_name": "Hause",
        "email": "ahause1d@devhub.com",
        "gender": "Male",
        "ip_address": "189.4.184.23"
    }, {
        "id": 51,
        "first_name": "Eddie",
        "last_name": "Herkess",
        "email": "eherkess1e@buzzfeed.com",
        "gender": "Female",
        "ip_address": "196.180.11.5"
    }, {
        "id": 52,
        "first_name": "Halette",
        "last_name": "Ghiron",
        "email": "hghiron1f@cargocollective.com",
        "gender": "Female",
        "ip_address": "122.100.37.196"
    }, {
        "id": 53,
        "first_name": "Antonie",
        "last_name": "Petrusch",
        "email": "apetrusch1g@qq.com",
        "gender": "Female",
        "ip_address": "31.241.130.25"
    }, {
        "id": 54,
        "first_name": "Alexio",
        "last_name": "Henfre",
        "email": "ahenfre1h@cargocollective.com",
        "gender": "Male",
        "ip_address": "29.66.135.109"
    }, {
        "id": 55,
        "first_name": "Elwood",
        "last_name": "Zannutti",
        "email": "ezannutti1i@walmart.com",
        "gender": "Male",
        "ip_address": "42.121.234.46"
    }, {
        "id": 56,
        "first_name": "Averill",
        "last_name": "Philo",
        "email": "aphilo1j@homestead.com",
        "gender": "Male",
        "ip_address": "17.69.25.30"
    }, {
        "id": 57,
        "first_name": "Gilbert",
        "last_name": "Wix",
        "email": "gwix1k@usatoday.com",
        "gender": "Male",
        "ip_address": "110.217.22.16"
    }, {
        "id": 58,
        "first_name": "Sammie",
        "last_name": "Bashford",
        "email": "sbashford1l@nps.gov",
        "gender": "Male",
        "ip_address": "90.127.6.245"
    }, {
        "id": 59,
        "first_name": "Lian",
        "last_name": "Bowness",
        "email": "lbowness1m@rediff.com",
        "gender": "Female",
        "ip_address": "36.251.151.226"
    }, {
        "id": 60,
        "first_name": "Helaina",
        "last_name": "Noury",
        "email": "hnoury1n@amazon.co.uk",
        "gender": "Female",
        "ip_address": "76.234.139.88"
    }, {
        "id": 61,
        "first_name": "Annabell",
        "last_name": "Kaming",
        "email": "akaming1o@nyu.edu",
        "gender": "Female",
        "ip_address": "42.9.158.249"
    }, {
        "id": 62,
        "first_name": "Abelard",
        "last_name": "Lavalde",
        "email": "alavalde1p@go.com",
        "gender": "Male",
        "ip_address": "221.65.230.225"
    }, {
        "id": 63,
        "first_name": "Vic",
        "last_name": "Willowby",
        "email": "vwillowby1q@senate.gov",
        "gender": "Male",
        "ip_address": "86.66.191.223"
    }, {
        "id": 64,
        "first_name": "Edgard",
        "last_name": "Bachnic",
        "email": "ebachnic1r@cnn.com",
        "gender": "Male",
        "ip_address": "244.240.8.30"
    }, {
        "id": 65,
        "first_name": "Maurene",
        "last_name": "Smead",
        "email": "msmead1s@sciencedirect.com",
        "gender": "Female",
        "ip_address": "214.154.181.43"
    }, {
        "id": 66,
        "first_name": "Mora",
        "last_name": "Bennion",
        "email": "mbennion1t@oaic.gov.au",
        "gender": "Female",
        "ip_address": "56.89.123.33"
    }, {
        "id": 67,
        "first_name": "Jordan",
        "last_name": "Austing",
        "email": "jausting1u@ucsd.edu",
        "gender": "Female",
        "ip_address": "148.95.156.109"
    }, {
        "id": 68,
        "first_name": "Tandie",
        "last_name": "Besantie",
        "email": "tbesantie1v@quantcast.com",
        "gender": "Female",
        "ip_address": "63.0.45.223"
    }, {
        "id": 69,
        "first_name": "Fons",
        "last_name": "O'Leary",
        "email": "foleary1w@si.edu",
        "gender": "Male",
        "ip_address": "166.135.143.113"
    }, {
        "id": 70,
        "first_name": "Viki",
        "last_name": "Warne",
        "email": "vwarne1x@rambler.ru",
        "gender": "Female",
        "ip_address": "43.116.13.78"
    }, {
        "id": 71,
        "first_name": "Rory",
        "last_name": "Oliphand",
        "email": "roliphand1y@ebay.co.uk",
        "gender": "Female",
        "ip_address": "214.151.177.66"
    }, {
        "id": 72,
        "first_name": "Chicky",
        "last_name": "McEachern",
        "email": "cmceachern1z@example.com",
        "gender": "Male",
        "ip_address": "240.204.48.208"
    }, {
        "id": 73,
        "first_name": "Paulina",
        "last_name": "Dallander",
        "email": "pdallander20@google.es",
        "gender": "Female",
        "ip_address": "20.97.122.211"
    }, {
        "id": 74,
        "first_name": "Denny",
        "last_name": "Pottiphar",
        "email": "dpottiphar21@de.vu",
        "gender": "Female",
        "ip_address": "229.59.173.134"
    }, {
        "id": 75,
        "first_name": "Ferris",
        "last_name": "Leyzell",
        "email": "fleyzell22@europa.eu",
        "gender": "Male",
        "ip_address": "130.138.176.178"
    }, {
        "id": 76,
        "first_name": "Willi",
        "last_name": "Ferrarotti",
        "email": "wferrarotti23@opera.com",
        "gender": "Female",
        "ip_address": "184.51.217.1"
    }, {
        "id": 77,
        "first_name": "Wallace",
        "last_name": "Ropars",
        "email": "wropars24@gizmodo.com",
        "gender": "Male",
        "ip_address": "210.23.110.102"
    }, {
        "id": 78,
        "first_name": "Brigit",
        "last_name": "Dunnan",
        "email": "bdunnan25@prnewswire.com",
        "gender": "Female",
        "ip_address": "62.188.186.223"
    }, {
        "id": 79,
        "first_name": "Samuele",
        "last_name": "Hebble",
        "email": "shebble26@dailymail.co.uk",
        "gender": "Male",
        "ip_address": "48.35.22.19"
    }, {
        "id": 80,
        "first_name": "Maurits",
        "last_name": "Ternouth",
        "email": "mternouth27@home.pl",
        "gender": "Male",
        "ip_address": "152.155.188.22"
    }, {
        "id": 81,
        "first_name": "Effie",
        "last_name": "Totman",
        "email": "etotman28@accuweather.com",
        "gender": "Female",
        "ip_address": "74.126.203.73"
    }, {
        "id": 82,
        "first_name": "Emmy",
        "last_name": "Piken",
        "email": "epiken29@usa.gov",
        "gender": "Male",
        "ip_address": "133.114.192.201"
    }, {
        "id": 83,
        "first_name": "Laurie",
        "last_name": "Currom",
        "email": "lcurrom2a@imageshack.us",
        "gender": "Male",
        "ip_address": "63.214.103.101"
    }, {
        "id": 84,
        "first_name": "Minor",
        "last_name": "Langan",
        "email": "mlangan2b@barnesandnoble.com",
        "gender": "Male",
        "ip_address": "219.77.3.194"
    }, {
        "id": 85,
        "first_name": "Abbi",
        "last_name": "Peirone",
        "email": "apeirone2c@acquirethisname.com",
        "gender": "Female",
        "ip_address": "186.28.236.215"
    }, {
        "id": 86,
        "first_name": "Dill",
        "last_name": "Huke",
        "email": "dhuke2d@amazonaws.com",
        "gender": "Male",
        "ip_address": "132.4.107.157"
    }, {
        "id": 87,
        "first_name": "Heywood",
        "last_name": "Graddell",
        "email": "hgraddell2e@123-reg.co.uk",
        "gender": "Male",
        "ip_address": "145.98.177.127"
    }, {
        "id": 88,
        "first_name": "Mariel",
        "last_name": "Spadeck",
        "email": "mspadeck2f@squidoo.com",
        "gender": "Female",
        "ip_address": "227.23.223.112"
    }, {
        "id": 89,
        "first_name": "Domenic",
        "last_name": "Cadwaladr",
        "email": "dcadwaladr2g@elegantthemes.com",
        "gender": "Male",
        "ip_address": "252.70.183.53"
    }, {
        "id": 90,
        "first_name": "Petronille",
        "last_name": "Bruno",
        "email": "pbruno2h@howstuffworks.com",
        "gender": "Female",
        "ip_address": "38.92.25.225"
    }, {
        "id": 91,
        "first_name": "Catharina",
        "last_name": "Mapstone",
        "email": "cmapstone2i@booking.com",
        "gender": "Female",
        "ip_address": "59.101.80.225"
    }, {
        "id": 92,
        "first_name": "Violetta",
        "last_name": "Ernke",
        "email": "vernke2j@weebly.com",
        "gender": "Female",
        "ip_address": "88.203.162.23"
    }, {
        "id": 93,
        "first_name": "Kai",
        "last_name": "Dur",
        "email": "kdur2k@comcast.net",
        "gender": "Female",
        "ip_address": "156.180.69.229"
    }, {
        "id": 94,
        "first_name": "Reinaldos",
        "last_name": "Delgado",
        "email": "rdelgado2l@dailymail.co.uk",
        "gender": "Male",
        "ip_address": "204.141.41.38"
    }, {
        "id": 95,
        "first_name": "Lorene",
        "last_name": "Franey",
        "email": "lfraney2m@imageshack.us",
        "gender": "Female",
        "ip_address": "8.191.123.230"
    }, {
        "id": 96,
        "first_name": "Andree",
        "last_name": "Spring",
        "email": "aspring2n@usnews.com",
        "gender": "Female",
        "ip_address": "44.113.208.215"
    }, {
        "id": 97,
        "first_name": "Aloysia",
        "last_name": "Clue",
        "email": "aclue2o@nba.com",
        "gender": "Female",
        "ip_address": "70.158.73.1"
    }, {
        "id": 98,
        "first_name": "Dar",
        "last_name": "Motherwell",
        "email": "dmotherwell2p@gmpg.org",
        "gender": "Male",
        "ip_address": "188.246.163.25"
    }, {
        "id": 99,
        "first_name": "Emmett",
        "last_name": "Marsden",
        "email": "emarsden2q@eepurl.com",
        "gender": "Male",
        "ip_address": "196.63.51.228"
    }, {
        "id": 100,
        "first_name": "Emmaline",
        "last_name": "Cruden",
        "email": "ecruden2r@netscape.com",
        "gender": "Female",
        "ip_address": "231.40.247.72"
    }
];
